"""Drop cycle_id from applicant table

Revision ID: 281a0262d286
Revises: d79a5adf2de9
Create Date: 2025-03-09 17:23:53.452671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281a0262d286'
down_revision: Union[str, None] = 'd79a5adf2de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('applicant_cycle_id_fkey', 'applicant', type_='foreignkey')
    op.drop_column('applicant', 'cycle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('cycle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('applicant_cycle_id_fkey', 'applicant', 'recruitment_cycle', ['cycle_id'], ['cycle_id'])
    # ### end Alembic commands ###
