"""Add more information fields to member table

Revision ID: 421e74be8bd0
Revises: 1ed70c55d115
Create Date: 2025-03-12 15:28:16.435677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421e74be8bd0'
down_revision: Union[str, None] = '1ed70c55d115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE mentorship_activity CASCADE')
    op.execute('DROP TABLE mentorship_group CASCADE')
    op.add_column('member', sa.Column('tamu_email', sa.String(length=255), nullable=False))
    op.add_column('member', sa.Column('grad_sem', sa.String(length=255), nullable=False))
    op.add_column('member', sa.Column('grad_year', sa.Integer(), nullable=False))
    op.add_column('member', sa.Column('probation', sa.Boolean(), nullable=False))
    op.add_column('member', sa.Column('linkedin', sa.String(length=255), nullable=False))
    op.add_column('member', sa.Column('insta', sa.String(length=255), nullable=False))
    op.add_column('member', sa.Column('birthday_month', sa.Integer(), nullable=False))
    op.add_column('member', sa.Column('birthday_day', sa.Integer(), nullable=False))
    op.add_column('member', sa.Column('birthday_year', sa.Integer(), nullable=False))
    # op.drop_constraint('member_mentorship_id_fkey', 'member', type_='foreignkey')
    op.drop_column('member', 'mentorship_id')
    op.drop_column('member', 'standing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('standing', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('mentorship_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.create_foreign_key('member_mentorship_id_fkey', 'member', 'mentorship_group', ['mentorship_id'], ['mentorship_id'])
    op.drop_column('member', 'birthday_year')
    op.drop_column('member', 'birthday_day')
    op.drop_column('member', 'birthday_month')
    op.drop_column('member', 'insta')
    op.drop_column('member', 'linkedin')
    op.drop_column('member', 'probation')
    op.drop_column('member', 'grad_year')
    op.drop_column('member', 'grad_sem')
    op.drop_column('member', 'tamu_email')
    op.create_table('mentorship_group',
    sa.Column('mentorship_id', sa.INTEGER(), server_default=sa.text("nextval('mentorship_group_mentorship_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('lead_mentor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lead_mentor_id'], ['member.member_id'], name='fk_mentorship_group_lead_mentor_id_member'),
    sa.PrimaryKeyConstraint('mentorship_id', name='mentorship_group_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('mentorship_activity',
    sa.Column('activity_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mentorship_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorship_group.mentorship_id'], name='mentorship_activity_mentorship_id_fkey'),
    sa.PrimaryKeyConstraint('activity_id', name='mentorship_activity_pkey')
    )
    # ### end Alembic commands ###
