"""Delete applicant_id from application

Revision ID: 4ef7169045db
Revises: a67b21dbb4c9
Create Date: 2025-03-08 23:02:34.748446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef7169045db'
down_revision: Union[str, None] = 'a67b21dbb4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_question_score', 'application_question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('app_response', 'application_question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('application_applicant_id_fkey', 'application', type_='foreignkey')
    op.drop_column('application', 'applicant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('application_applicant_id_fkey', 'application', 'applicant', ['applicant_id'], ['applicant_id'])
    op.alter_column('app_response', 'application_question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('app_question_score', 'application_question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
