"""Change recruitment_id to cycle_id in Applicant table

Revision ID: 71239d99ad82
Revises: 4ef7169045db
Create Date: 2025-03-09 10:50:30.943939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71239d99ad82'
down_revision: Union[str, None] = '4ef7169045db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('cycle_id', sa.Integer(), nullable=False))
    op.drop_constraint('applicant_recruitment_id_fkey', 'applicant', type_='foreignkey')
    op.create_foreign_key(None, 'applicant', 'recruitment_cycle', ['cycle_id'], ['cycle_id'])
    op.drop_column('applicant', 'recruitment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('recruitment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applicant', type_='foreignkey')
    op.create_foreign_key('applicant_recruitment_id_fkey', 'applicant', 'recruitment_cycle', ['recruitment_id'], ['cycle_id'])
    op.drop_column('applicant', 'cycle_id')
    # ### end Alembic commands ###
