"""Rid of name and add uin in applicant table

Revision ID: d79a5adf2de9
Revises: 71239d99ad82
Create Date: 2025-03-09 17:09:36.568739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79a5adf2de9'
down_revision: Union[str, None] = '71239d99ad82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('uin', sa.String(length=255), nullable=False))
    op.drop_column('applicant', 'last_name')
    op.drop_column('applicant', 'first_name')
    op.add_column('member', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('member', sa.Column('last_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'last_name')
    op.drop_column('member', 'first_name')
    op.add_column('applicant', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('applicant', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('applicant', 'uin')
    # ### end Alembic commands ###
