"""Delete display_order column from ApplicationQuestion table

Revision ID: 0533d2a0f459
Revises: 281a0262d286
Create Date: 2025-03-10 12:59:34.553210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0533d2a0f459'
down_revision: Union[str, None] = '281a0262d286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_question', 'display_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_question', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
