"""Change committee name and division to enum types

Revision ID: 33c550ed9e91
Revises: 196039e5a525
Create Date: 2025-03-07 22:40:01.741746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c550ed9e91'
down_revision: Union[str, None] = '196039e5a525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committee', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('CAREER_FAIR', 'CORPORATE', 'ENG_DEV', 'FINANCE', 'PROTRIP', 'EWEEK', 'ENVISION', 'PHILANTHROPY', 'SPECIAL_EVENTS', 'LEGISLATION', 'SAGR', 'STUDENT_RELATIONS', 'IR', 'MARKETING', 'SYSAD', 'MEMBERSHIP', name='committeename'),
               existing_nullable=True)
    op.alter_column('committee', 'division',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('DEVELOPMENT', 'EXTERNAL', 'INTERNAL', 'OPERATIONS', name='committeedivision'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committee', 'division',
               existing_type=sa.Enum('DEVELOPMENT', 'EXTERNAL', 'INTERNAL', 'OPERATIONS', name='committeedivision'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('committee', 'name',
               existing_type=sa.Enum('CAREER_FAIR', 'CORPORATE', 'ENG_DEV', 'FINANCE', 'PROTRIP', 'EWEEK', 'ENVISION', 'PHILANTHROPY', 'SPECIAL_EVENTS', 'LEGISLATION', 'SAGR', 'STUDENT_RELATIONS', 'IR', 'MARKETING', 'SYSAD', 'MEMBERSHIP', name='committeename'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
